export const USER__LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER__LOGIN = "USER_LOGIN";
export const USER__LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_LOADING = "USER_REGISTER_LOADING";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const ITEM_ADD_SUCCESS = "ITEM_ADD_SUCCESS";

export const GET_EMPLOYEE_SUCCESS = "GET_EMPLOYEE_SUCCESS";
export const GET_EMPLOYEE_LOADING = "GET_EMPLOYEE_LOADING";
export const GET_EMPLOYEE_FAILED = "GET_EMPLOYEE_FAILED";

export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_LOADING = "ADD_EMPLOYEE_LOADING";
export const ADD_EMPLOYEE_FAILED = "ADD_EMPLOYEE_FAILED";

export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_LOADING = "UPDATE_EMPLOYEE_LOADING";
export const UPDATE_EMPLOYEE_FAILED = "UPDATE_EMPLOYEE_FAILED";

export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_LOADING = "DELETE_EMPLOYEE_LOADING";
export const DELETE_EMPLOYEE_FAILED = "DELETE_EMPLOYEE_FAILED";

export const GET_ONE_EMPLOYEE_SUCCESS = "GET_ONE_EMPLOYEE_SUCCESS";
export const GET_ONE_EMPLOYEE_LOADING = "GET_ONE_EMPLOYEE_LOADING";
export const GET_ONE_EMPLOYEE_FAILED = "GET_ONE_EMPLOYEE_FAILED";

// export const USER__LOGIN = "USER__LOGIN";
// export const USER__LOGIN_FAILED = "USER__LOGIN_FAILED";
// export const USER__LOGIN_SUCCESS = "USER__LOGIN_SUCCESS";
// export const USER__REGISTER_FAILED = "USER__REGISTER_FAILED";
